website/models.py
from .extensions import db

class Users(db.Model):
    """Template table for user in database"""
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(50))

website/__init__.py
"""Initialize Flask app"""
from flask import Flask
from .extensions import db
from datetime import timedelta


def create_app():
    """Create Flask application"""
    app = Flask(__name__, instance_relative_config=False)
    # SQL configs
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # required secret key for data transfer to backend
    app.secret_key = "team7"
    # session timeout
    app.permanent_session_lifetime = timedelta(minutes=3)

    #Initialize SQLAlchemy object
    db.init_app(app)
    
    #Import the parts of the application
    from .home.routes import home_bp
    from .admin.routes import admin_bp
    from .profile.routes import profile_bp

    #Register Blueprints
    app.register_blueprint(home_bp, url_prefix='/')
    app.register_blueprint(admin_bp, url_prefix='/admin')
    app.register_blueprint(profile_bp,url_prefix='/user')
    
    return app 

website/admin/routes.py
from flask import Blueprint, render_template, jsonify, request, redirect, url_for
from pika import BlockingConnection, ConnectionParameters, BasicProperties
from ..extensions import db
from ..models import Users


#Blueprint Config
admin_bp = Blueprint(
    'admin_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

# RabbitMQ connection parameters
rabbitmq_host = 'localhost'
rabbitmq_port = 5672
rabbitmq_queue = 'hello'


def send_message_to_rabbitmq(message):
    """Takes message from client to send to rabbit exchange"""
    connection = BlockingConnection(ConnectionParameters(rabbitmq_host))
    channel = connection.channel()
    channel.queue_declare(queue=rabbitmq_queue)
    channel.basic_publish(exchange='', routing_key=rabbitmq_queue, body=message)
    connection.close()

@admin_bp.route("/")
def home():
    return "<p>Admin Home</p>"


@admin_bp.route("/view")
def view():
    return render_template("view.html", values=Users.query.all())

@admin_bp.route('/send-message', methods=['POST'])
def send_message():
    data = request.json
    message = data.get('message')
    if not message:
        # TODO Flash message instead
        return jsonify({'error': 'Message is required'}), 400
    send_message_to_rabbitmq(message)
    # TODO flash message and return to admin home
    return jsonify({'status': 'Message sent successfully'}), 200


@admin_bp.route('/receive-message', methods=['GET'])
def receive_message():
    connection = BlockingConnection(ConnectionParameters(rabbitmq_host))
    channel = connection.channel()
    channel.queue_declare(queue=rabbitmq_queue)
    method_frame, header_frame, body = channel.basic_get(queue=rabbitmq_queue)
    messages = []
    if method_frame:
        channel.basic_ack(delivery_tag=method_frame.delivery_tag)
        return render_template('receive_message.html', messages=messages)
    else:
       return redirect(url_for("home"))
    
@admin_bp.route("/delete", methods=['POST'])
def delete():
    """Deletes all users in database"""
    found_user = Users.query.filter_by(name=user).delete()
    for user in found_user:
        user.delete()
    return redirect(url_for("home"))

website/home/routes.py
from flask import (Blueprint, render_template, 
                   session, request, redirect, flash, url_for)
from ..extensions import db
from ..models import Users

#Blueprint Config
home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@home_bp.route('/')
def home():
    """Returns home page"""
    return render_template("index.html")

website/profile/routes.py
from flask import (Blueprint, render_template,
                    session, request, redirect, flash, url_for)
from ..extensions import db
from ..models import Users

#Blueprint Config
profile_bp = Blueprint(
    'profile_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@profile_bp.route('/login', methods=['POST', 'GET'])
def login():
    """Takes form data saves it into a session and redirects to user page"""
    if request.method == "POST":
        session.permanent = True
        user = request.form["nm"]
        session ["user"] = user

        #query database for existing users
        found_user = Users.query.filter_by(name=user).first()
        if found_user:
            session["email"] = found_user.email
        else:
            usr = Users(user, "")
            db.session.add(usr)
            db.session.commit()

        flash(f"Login Successful!")
        return redirect(url_for("user"))
    else:
        if "user" in session:
            flash("Already Logged In!")
            return redirect(url_for("account"))
     
    return render_template("login.html")


@profile_bp.route("/logout")
def logout():
    return "<p>Log Out</p>"


@profile_bp.route("/signup")
def sign_up():
    return render_template("sign_up.html")


@profile_bp.route("/account")
def account():
    return "<p>My Account</p>"

website/user/routes.py
from flask import (Blueprint, render_template,
                    session, request, redirect, flash, url_for)
from ..extensions import db
from ..models import Users

#Blueprint Config
user_bp = Blueprint(
    'user_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@user_bp.route('/login', methods=['POST', 'GET'])
def login():
    """Takes form data saves it into a session and redirects to user page"""
    if request.method == "POST":
        session.permanent = True
        user = request.form["nm"]
        session ["user"] = user

        #query database for existing users
        found_user = Users.query.filter_by(name=user).first()
        if found_user:
            session["email"] = found_user.email
        else:
            usr = Users(user, "")
            db.session.add(usr)
            db.session.commit()

        flash(f"Login Successful!")
        return redirect(url_for("user"))
    else:
        if "user" in session:
            flash("Already Logged In!")
            return redirect(url_for("user"))
     
    return render_template("login.html")


@user_bp.route("/logout")
def logout():
    return "<p>Log Out</p>"


@user_bp.route("/sign-up")
def sign_up():
    return "<p>Sign Up</p>"


@user_bp.route("/account")
def account():
    return "<p>My Account</p>"

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% block head %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {# custom style sheet #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css')}}">
    <title>{% block title %}Test Site{% endblock title %}</title>
</head>
{% endblock  %}

<body>
    {# bootstrap nav #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{url_for('home_bp.home')}}">InternConnect</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('profile_bp.sign_up')}}">SignUp</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        User Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('profile_bp.login') }}">Login</a>
                        <a class="dropdown-item" href="{{ url_for('profile_bp.account') }}">My Account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ url_for('profile_bp.logout') }}">Logout</a>
                    </div>
                </li>
            </ul>
            <span class="navbar-text">
                <h4><em>Connecting Talent, Fueling Futures.</em></h4>
            </span>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Database" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container-fluid">
        {% block content  %}
        {% endblock  %}
    </div>

    <script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

website/templates/blueprintinfo.html
<div class="blueprint-info">
    <h3>Blueprint Info</h3>
    <ul class="page-properties">
      <li><span class="attribute-title">Blueprint:</span> <span class="attribute-value">{{ request.blueprint }}</span></li>
      <li><span class="attribute-title">Template:</span> <span class="attribute-value">{{ self._TemplateReference__context.name }}</span></li>
      <li><span class="attribute-title">View:</span> <span class="attribute-value">{{ request.endpoint }}</span></li>
      <li><span class="attribute-title">Route:</span> <span class="attribute-value">{{ request.path }}</span></li>
    </ul>
</div>